settings:
  title: 'pxlAPI status'
  url: 'https://status.pxlapi.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: website # unique identifier
    name: pxlapi.dev
    description: 'pxlAPI website' # default=empty
    url: 'https://pxlapi.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: api
    name: api.pxlapi.dev
    description: 'pxlAPI backend'
    url: 'https://api.pxlapi.dev/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
